version: '3.3'

services:
  nestjs-api:
    container_name: nestjs-api
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./public:/app/public
      - ./views:/app/views
      - ./settings:/app/settings
    ports:
      - ${PORT}:3000
    env_file:
      - ./.env